//categories
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAILED = 'LOAD_CATEGORIES_FAILED';

//question types
export const GET_CATEGORY_TYPES= 'GET_CATEGORY_TYPES'
export const GET_DIFFICULTY_TYPE= 'GET_DIFFICULTY_TYPE'

